version: '3.5'

services:
  pycontw-2025-frontend:
    container_name: pycontw-2025-frontend
    restart: always
    build:
      context: .
    networks:
      - network

networks:
    network:
        external: true
        name: network-2025
